import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import LinkContainer from "../components/LinkContainer";

const Home: NextPage = () => {
  return (
    <div className="flex flex-col h-screen m-0 p-0">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="items-center justify-center flex flex-auto flex-col">
        <LinkContainer />
        <h1 className="text-2xl font-bold underline text-blue-800 ">
          Under Contruction 🚧
        </h1>
      </main>
      <footer className="bg-blue-600 h-[10vh] flex items-center justify-center">
        <a
          href="https://github.com/amar-jay"
          className="text-center text-white decoration-none"
        >
          Built by Amar Jay 🤧
        </a>
      </footer>
    </div>
  );
};

export default Home;
